Sys.setenv(RETICULATE_PYTHON = "C:/Python27/ArcGISx6410.5")
library(reticulate)
library(jsonlite)
library(httr)
library(tidyverse)
library(pool)
library(dbplyr)
library(DBI)
source("utils_expanded.R")

source("agol-download.R")
source("data-upload.R")
